/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace LandRegistry {
      
    export type OwnerRecordStruct = {owner: AddressLike, timestamp: BigNumberish, action: string}

    export type OwnerRecordStructOutput = [owner: string, timestamp: bigint, action: string] & {owner: string, timestamp: bigint, action: string }
  

    export type LandDetailsStruct = {landId: BytesLike, currentOwner: AddressLike, location: string, areaSqMeters: BigNumberish, exists: boolean}

    export type LandDetailsStructOutput = [landId: string, currentOwner: string, location: string, areaSqMeters: bigint, exists: boolean] & {landId: string, currentOwner: string, location: string, areaSqMeters: bigint, exists: boolean }
  
    }

  export interface LandRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getHistory" | "getLandDetails" | "getOwner" | "registerLand" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LandRegistered" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'getHistory', values: [string]): string;
encodeFunctionData(functionFragment: 'getLandDetails', values: [string]): string;
encodeFunctionData(functionFragment: 'getOwner', values: [string]): string;
encodeFunctionData(functionFragment: 'registerLand', values: [string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [string, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLandDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerLand', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace LandRegisteredEvent {
      export type InputTuple = [landId: BytesLike, owner: AddressLike, location: string, timestamp: BigNumberish];
      export type OutputTuple = [landId: string, owner: string, location: string, timestamp: bigint];
      export interface OutputObject {landId: string, owner: string, location: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [landId: BytesLike, previousOwner: AddressLike, newOwner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [landId: string, previousOwner: string, newOwner: string, timestamp: bigint];
      export interface OutputObject {landId: string, previousOwner: string, newOwner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LandRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): LandRegistry;
    waitForDeployment(): Promise<this>;

    interface: LandRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getHistory: TypedContractMethod<
      [_landId: string, ],
      [LandRegistry.OwnerRecordStructOutput[]],
      'view'
    >
    

    
    getLandDetails: TypedContractMethod<
      [_landId: string, ],
      [LandRegistry.LandDetailsStructOutput],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [_landId: string, ],
      [string],
      'view'
    >
    

    
    registerLand: TypedContractMethod<
      [_landId: string, _location: string, _areaSqMeters: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [_landId: string, _newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getHistory'): TypedContractMethod<
      [_landId: string, ],
      [LandRegistry.OwnerRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getLandDetails'): TypedContractMethod<
      [_landId: string, ],
      [LandRegistry.LandDetailsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [_landId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerLand'): TypedContractMethod<
      [_landId: string, _location: string, _areaSqMeters: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [_landId: string, _newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LandRegistered'): TypedContractEvent<LandRegisteredEvent.InputTuple, LandRegisteredEvent.OutputTuple, LandRegisteredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'LandRegistered(bytes32,address,string,uint256)': TypedContractEvent<LandRegisteredEvent.InputTuple, LandRegisteredEvent.OutputTuple, LandRegisteredEvent.OutputObject>;
      LandRegistered: TypedContractEvent<LandRegisteredEvent.InputTuple, LandRegisteredEvent.OutputTuple, LandRegisteredEvent.OutputObject>;
    

      'OwnershipTransferred(bytes32,address,address,uint256)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }